#ifndef BOMBSTART2D_H
#define BOMBSTART2D_H

#include "JSystem/JKernel/JKRHeap.h"

class BombStart2D { // Autogenerated
public:
    BombStart2D(JKRHeap *); // 0x80198214
    void init(); // 0x801984d4
    void draw(); // 0x80198528
    void calc(); // 0x801985c4
    void start(); // 0x8019862c
    // Inline/Unused
    ~BombStart2D();
}; // class BombStart2D
#endif // BOMBSTART2D_H
