#ifndef CANNOTSAVEG2D_H
#define CANNOTSAVEG2D_H

#include "JSystem/JKernel/JKRHeap.h"

class CanNotSaveG2D { // Autogenerated
public:
    CanNotSaveG2D(JKRHeap *); // 0x80194fe0
    void init(); // 0x801950d4
    void draw(); // 0x80195124
    void calc(); // 0x801951c0
    // Inline/Unused
    ~CanNotSaveG2D();
}; // class CanNotSaveG2D
#endif // CANNOTSAVEG2D_H
