#ifndef COURSENAME2D_H
#define COURSENAME2D_H

#include "kartEnums.h"

#include "JSystem/JKernel/JKRArchive.h"

class CourseName2D { // Autogenerated
public:
    CourseName2D(JKRArchive *); // 0x80190a94
    ~CourseName2D(); // 0x80190b5c
    void *getCourseNameTexture(ECourseID); // 0x80190bb0
    static CourseName2D *mCourseName2D; // 0x80416378
}; // class CourseName2D
#endif // COURSENAME2D_H
