#ifndef CUP2D_H
#define CUP2D_H

#include "kartEnums.h"

#include "JSystem/JKernel/JKRArchive.h"

class Cup2D { // Autogenerated
public:
    Cup2D(JKRArchive *); // 0x80197f10
    ~Cup2D(); // 0x80197fc0
    void *getCupTexture(ERaceGpCup, int); // 0x80198014
    static Cup2D *mCup2D; // 0x80416388
}; // class Cup2D
#endif // CUP2D_H
