#ifndef GO2D_H
#define GO2D_H

#include "JSystem/JKernel/JKRHeap.h"

#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"

class Go2DParam : public JORReflexible {
public:
    // Inline/Unused
    Go2DParam();
    virtual ~Go2DParam() {}
};

class Go2DHioNode : public HioNode {
public:
    Go2DHioNode();
    virtual ~Go2DHioNode() {}

    Go2DParam mParam;
};

class Go2D { // Autogenerated
 public:
    Go2D(JKRHeap *); // 0x8016ea58
    void init();     // 0x8016ebec
    void draw();     // 0x8016ecac
    void calc();     // 0x8016ed58
    // Inline/Unused
    ~Go2D();

    void reset() { init(); }
    void setDrawFlag(bool enable) { mDrawFlag = enable; }
private:
    PLACEHOLDER_BYTES(0, 0x30);
    bool mDrawFlag; // 30
    PLACEHOLDER_BYTES(0x31, 0x34);
}; // class Go2D
#endif // GO2D_H
