#ifndef GO3212D_H
#define GO3212D_H

#include "JSystem/JKernel/JKRHeap.h"

#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"

class Go3212DParam : public JORReflexible {
public:
    // Inline/Unused
    Go3212DParam();
    virtual ~Go3212DParam() {}
};

class Go3212DHioNode : public HioNode {
public:
    Go3212DHioNode();
    virtual ~Go3212DHioNode() {}

    Go3212DParam mParam;
};

class Go3212D { // Autogenerated
public:
    Go3212D(JKRHeap *); // 0x80183460
    void init(); // 0x801835f8
    void draw(); // 0x80183680
    void calc(); // 0x8018372c
    // Inline/Unused
    ~Go3212D();

    void reset() { init(); }
    bool isStart() { return mIsStart; }
    void start() { mIsStart = true; }
private:
    PLACEHOLDER_BYTES(0, 0x24);
    bool mIsStart;
    PLACEHOLDER_BYTES(0x25, 0x28);
}; // class Go3212D
#endif // GO3212D_H
