#ifndef K2DPICTURE_H
#define K2DPICTURE_H

#include "JSystem/JGeometry/Box.h"
#include "JSystem/JUtility/TColor.h"

class K2DPicture { // Autogenerated
public:
    void drawK2D(f32, f32, f32, f32, bool); // 0x8013b9e8
    void setTevModeK2D(); // 0x8013bd34
    void makeMatrix(f32, f32); // 0x8013c0fc
    static u8 mK2DGlobalAlpha; // 0x804145a8
    // Inline/Unused
    void drawOutK2D(const JGeometry::TBox2f &, const JGeometry::TBox2f &);
    ~K2DPicture();
    // Inline
    void getNewColor(JUTColor *); // 0x8013bbf8
}; // class K2DPicture
#endif // K2DPICTURE_H
