#ifndef PRERACE2D_H
#define PRERACE2D_H

#include "JSystem/J2D/J2DPicture.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "JSystem/JORReflexible.h"
#include "Kaneshige/HioMgr.h"

class PreRace2DParam : public JORReflexible {
public:
    // Inline/Unused
    PreRace2DParam();
    virtual ~PreRace2DParam() {}
};

class PreRace2DHioNode : public HioNode {
public:
    PreRace2DHioNode();
    virtual ~PreRace2DHioNode() {}

    PreRace2DParam mParam;
};

class PreRace2D { // Autogenerated
public:
    PreRace2D(JKRHeap *); // 0x8016cecc
    void init(); // 0x8016d754
    void draw(); // 0x8016d814
    void calc(); // 0x8016d8d8
    void setGP(); // 0x8016db38
    void setVS(); // 0x8016df3c
    void setTA(); // 0x8016df40
    void setBalloon(); // 0x8016df44
    void setBomb(); // 0x8016e13c
    void setEscape(); // 0x8016e334
    void setLap(); // 0x8016e524
    void setMirror(); // 0x8016e6d0
    void changeTexture(const char *, J2DPicture *); // 0x8016e84c
    void start(); // 0x8016e8b0
    static const u64 mPreRaceBckTag[2]; // 0x80371070
    // Inline/Unused
    ~PreRace2D();
}; // class PreRace2D
#endif // PRERACE2D_H
