#ifndef JUGEMHEADITEM_H
#define JUGEMHEADITEM_H

#include "JSystem/JGeometry/Matrix.h"
#include "Sato/GeographyObj.h"
#include "Sato/J3DAnmObject.h"
#include "types.h"

class TJugemHeadItem : public GeographyObj {
public:
    TJugemHeadItem(u32 id) : GeographyObj(id), mJugemParentPtr(nullptr) {
    }
    virtual ~TJugemHeadItem() {}
    virtual void calc() {} 
    virtual void setPosition(const JGeometry::TVec3f &pos) { mPos.set(pos); } // 80
    virtual void setRMtx(const JGeometry::TPos3f &rMtx) { mRotMtx.set(rMtx.mMtx);  } // 84
    virtual void hideModel(u32 p1) { mModel.clipAll(p1, false); } // 88
    virtual void show(u8) { clrObjFlagHidding(); } // 8c
    virtual void hide() { setObjFlagHidding(); } // 90
    virtual void hideAll() { hide(); } // 94

public:
    int mJugemParentPtr;
};

class TJugemHeadHear : public TJugemHeadItem {
public:
    TJugemHeadHear();
    virtual ~TJugemHeadHear();
    virtual void reset();
    virtual void hideModel(u32 p1) { mModel.clipAll(p1, false); }
    virtual const char *getBmdFileName();
};

class TJugemHeadLamp : public TJugemHeadItem { // Autogenerated
public:
    TJugemHeadLamp(); // 0x802bae5c
    virtual ~TJugemHeadLamp(); // 0x802bafa8
    virtual void reset(); // 0x802bb078
    virtual void loadAnimation(); // 0x802bb110
    virtual void createModel(JKRSolidHeap *, u32); // 0x802bb178
    virtual const char *getBmdFileName(); // 0x802bb2d0
    virtual void calc(); // 0x802bb2f8
    virtual void update(); // 0x802bb31c

    static J3DAnmTevRegKey *sJugemHeadLampBrkAnm; // 0x80417018
    static J3DAnmTransform *sJugemHeadLampBcaAnm; // 0x8041701c
    static J3DMtxCalc *sJugemHeadLampBcaMtxCalc;  // 0x80417020

    J3DAnmObjMaterial _150;   // 150
};

#endif // JUGEMHEADITEM_H
